### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by Kishan0708** [moderna/cordova-plugin-log#1]
Hello,

IN the beginning of the website you said "This plugin writes all cordova javascript logs into a file in a public folder (Android: sdCard, iOS: ~/Documents)." But at the end you say iOS is not supported yet.

When are you starting support for iOS?

**Comment by moderna** [comment]
With the posibility of remote debugging WebViews (android 4.4, ios 6) this plugin has become obsolete, thus we may never make an ios version of it.

Feel free to fork it and implement and ios version if you like (but be warned, the Android version is not cordova 6.x compatible and needs a total rewrite too).
